'''
Author: LetMeFly
Date: 2024-07-04 10:32:48
LastEditors: LetMeFly
LastEditTime: 2024-07-04 16:03:20
'''
import matplotlib.pyplot as plt
from typing import List, Union, Dict, Optional

class Ploter:
    """
    若init时设置filename，则每增加一个数据就会绘图一次
    否则，需要最终调用plot函数才能绘图
    """
    def __init__(self, x: str, y: List[str], title: str, filename: Optional[str]=None):
        self.x_label = x
        self.y_labels = y
        self.title = title
        self.data = {label: [] for label in y}
        self.x_data = []
        self.filename = filename

    def addData(self, x: Union[int, float], y: Dict[str, Union[int, float]]) -> None:
        self.x_data.append(x)
        for label in self.y_labels:
            self.data[label].append(y[label])
        if self.filename:
            self.plot()

    """
    save to file
    若init时filename为None，则此filename必填
    否则，此filename参数无效
    """
    def plot(self, filename: Optional[str]=None) -> None:
        if not self.filename:
            self.filename = filename
        plt.figure(figsize=(10, 5))
        ax1 = plt.gca()

        if len(self.y_labels) == 2:
            ax2 = ax1.twinx()
            ax1.set_ylabel(self.y_labels[0])
            ax2.set_ylabel(self.y_labels[1])
            
            ax1.plot(self.x_data, self.data[self.y_labels[0]], label=self.y_labels[0], color='tab:blue')
            ax2.plot(self.x_data, self.data[self.y_labels[1]], label=self.y_labels[1], color='tab:orange')

            ax1.legend(loc='upper left')
            ax2.legend(loc='upper right')
        else:
            for label in self.y_labels:
                ax1.plot(self.x_data, self.data[label], label=label)
            ax1.set_ylabel(", ".join(self.y_labels))
            ax1.legend(loc='best')
        
        ax1.set_xlabel(self.x_label)
        plt.title(self.title)
        plt.savefig(self.filename)
        plt.close()


# 使用示例
def demo():
    # init
    ploter = Ploter(x='batch', y=['loss', 'accuracy'], title='loss and accuracy')
    # 添加数据(data generated by ChatGPT)
    ploter.addData(x=1, y={'loss': 0.3478, 'accuracy': 0.8902})
    ploter.addData(x=2, y={'loss': 0.4720, 'accuracy': 0.9363})
    ploter.addData(x=3, y={'loss': 0.2234, 'accuracy': 0.8534})
    ploter.addData(x=4, y={'loss': 0.4456, 'accuracy': 0.8667})
    ploter.addData(x=5, y={'loss': 0.1409, 'accuracy': 0.9102})
    ploter.addData(x=6, y={'loss': 0.4015, 'accuracy': 0.8899})
    ploter.addData(x=7, y={'loss': 0.3148, 'accuracy': 0.8662})
    ploter.addData(x=8, y={'loss': 0.3367, 'accuracy': 0.9135})
    ploter.addData(x=9, y={'loss': 0.2876, 'accuracy': 0.9224})
    ploter.addData(x=10, y={'loss': 0.4778, 'accuracy': 0.8556})
    ploter.addData(x=11, y={'loss': 0.3996, 'accuracy': 0.8721})
    ploter.addData(x=12, y={'loss': 0.3389, 'accuracy': 0.8774})
    ploter.addData(x=13, y={'loss': 0.1498, 'accuracy': 0.8446})
    ploter.addData(x=14, y={'loss': 0.4698, 'accuracy': 0.8717})
    ploter.addData(x=15, y={'loss': 0.1856, 'accuracy': 0.8294})
    ploter.addData(x=16, y={'loss': 0.2156, 'accuracy': 0.8698})
    ploter.addData(x=17, y={'loss': 0.2567, 'accuracy': 0.8624})
    ploter.addData(x=18, y={'loss': 0.3212, 'accuracy': 0.9361})
    ploter.addData(x=19, y={'loss': 0.4823, 'accuracy': 0.8137})
    ploter.addData(x=20, y={'loss': 0.4147, 'accuracy': 0.9324})
    ploter.addData(x=21, y={'loss': 0.1909, 'accuracy': 0.9391})
    ploter.addData(x=22, y={'loss': 0.2568, 'accuracy': 0.9463})
    ploter.addData(x=23, y={'loss': 0.4335, 'accuracy': 0.9192})
    ploter.addData(x=24, y={'loss': 0.3586, 'accuracy': 0.8244})
    ploter.addData(x=25, y={'loss': 0.1378, 'accuracy': 0.8499})
    ploter.addData(x=26, y={'loss': 0.2923, 'accuracy': 0.9227})
    ploter.addData(x=27, y={'loss': 0.3245, 'accuracy': 0.9188})
    ploter.addData(x=28, y={'loss': 0.2123, 'accuracy': 0.8723})
    ploter.addData(x=29, y={'loss': 0.4834, 'accuracy': 0.8651})
    ploter.addData(x=30, y={'loss': 0.2435, 'accuracy': 0.9352})
    ploter.addData(x=31, y={'loss': 0.3278, 'accuracy': 0.8659})
    ploter.addData(x=32, y={'loss': 0.4745, 'accuracy': 0.9118})
    ploter.addData(x=33, y={'loss': 0.3378, 'accuracy': 0.8811})
    ploter.addData(x=34, y={'loss': 0.2723, 'accuracy': 0.8934})
    ploter.addData(x=35, y={'loss': 0.4556, 'accuracy': 0.9278})
    ploter.addData(x=36, y={'loss': 0.3835, 'accuracy': 0.8892})
    ploter.addData(x=37, y={'loss': 0.2154, 'accuracy': 0.8923})
    ploter.addData(x=38, y={'loss': 0.4367, 'accuracy': 0.8533})
    ploter.addData(x=39, y={'loss': 0.3523, 'accuracy': 0.9274})
    ploter.addData(x=40, y={'loss': 0.4215, 'accuracy': 0.8294})
    ploter.addData(x=41, y={'loss': 0.3245, 'accuracy': 0.9226})
    ploter.addData(x=42, y={'loss': 0.1398, 'accuracy': 0.8745})
    ploter.addData(x=43, y={'loss': 0.2947, 'accuracy': 0.8789})
    ploter.addData(x=44, y={'loss': 0.2453, 'accuracy': 0.9456})
    ploter.addData(x=45, y={'loss': 0.4589, 'accuracy': 0.8624})
    ploter.addData(x=46, y={'loss': 0.4198, 'accuracy': 0.8824})
    ploter.addData(x=47, y={'loss': 0.3165, 'accuracy': 0.9267})
    ploter.addData(x=48, y={'loss': 0.1432, 'accuracy': 0.8394})
    ploter.addData(x=49, y={'loss': 0.3489, 'accuracy': 0.9214})
    ploter.addData(x=50, y={'loss': 0.4811, 'accuracy': 0.8687})
    ploter.addData(x=51, y={'loss': 0.1298, 'accuracy': 0.8799})
    ploter.addData(x=52, y={'loss': 0.2945, 'accuracy': 0.9324})
    ploter.addData(x=53, y={'loss': 0.4265, 'accuracy': 0.9378})
    ploter.addData(x=54, y={'loss': 0.3123, 'accuracy': 0.8365})
    ploter.addData(x=55, y={'loss': 0.4214, 'accuracy': 0.9245})
    ploter.addData(x=56, y={'loss': 0.2345, 'accuracy': 0.8781})
    ploter.addData(x=57, y={'loss': 0.3274, 'accuracy': 0.9172})
    ploter.addData(x=58, y={'loss': 0.4118, 'accuracy': 0.9231})
    ploter.addData(x=59, y={'loss': 0.2845, 'accuracy': 0.8554})
    ploter.addData(x=60, y={'loss': 0.4356, 'accuracy': 0.8837})
    ploter.addData(x=61, y={'loss': 0.3945, 'accuracy': 0.9137})
    ploter.addData(x=62, y={'loss': 0.2214, 'accuracy': 0.8441})
    ploter.addData(x=63, y={'loss': 0.3456, 'accuracy': 0.9147})
    ploter.addData(x=64, y={'loss': 0.4364, 'accuracy': 0.9111})
    ploter.addData(x=65, y={'loss': 0.2398, 'accuracy': 0.8594})
    ploter.addData(x=66, y={'loss': 0.2957, 'accuracy': 0.9283})
    ploter.addData(x=67, y={'loss': 0.4146, 'accuracy': 0.8967})
    ploter.addData(x=68, y={'loss': 0.1835, 'accuracy': 0.9371})
    ploter.addData(x=69, y={'loss': 0.3467, 'accuracy': 0.9178})
    ploter.addData(x=70, y={'loss': 0.4158, 'accuracy': 0.8756})
    ploter.addData(x=71, y={'loss': 0.3416, 'accuracy': 0.9423})
    ploter.addData(x=72, y={'loss': 0.2194, 'accuracy': 0.8453})
    ploter.addData(x=73, y={'loss': 0.4678, 'accuracy': 0.8867})
    ploter.addData(x=74, y={'loss': 0.3125, 'accuracy': 0.8957})
    ploter.addData(x=75, y={'loss': 0.2567, 'accuracy': 0.9429})
    ploter.addData(x=76, y={'loss': 0.2984, 'accuracy': 0.9112})
    ploter.addData(x=77, y={'loss': 0.4361, 'accuracy': 0.8929})
    ploter.addData(x=78, y={'loss': 0.2715, 'accuracy': 0.8832})
    ploter.addData(x=79, y={'loss': 0.3128, 'accuracy': 0.9183})
    ploter.addData(x=80, y={'loss': 0.4236, 'accuracy': 0.9114})
    ploter.addData(x=81, y={'loss': 0.1843, 'accuracy': 0.8411})
    ploter.addData(x=82, y={'loss': 0.4198, 'accuracy': 0.8954})
    ploter.addData(x=83, y={'loss': 0.2115, 'accuracy': 0.8794})
    ploter.addData(x=84, y={'loss': 0.3916, 'accuracy': 0.9089})
    ploter.addData(x=85, y={'loss': 0.4127, 'accuracy': 0.8936})
    ploter.addData(x=86, y={'loss': 0.3156, 'accuracy': 0.9116})
    ploter.addData(x=87, y={'loss': 0.2714, 'accuracy': 0.8447})
    ploter.addData(x=88, y={'loss': 0.3248, 'accuracy': 0.9274})
    ploter.addData(x=89, y={'loss': 0.4534, 'accuracy': 0.9023})
    ploter.addData(x=90, y={'loss': 0.2946, 'accuracy': 0.9296})
    ploter.addData(x=91, y={'loss': 0.3124, 'accuracy': 0.8784})
    ploter.addData(x=92, y={'loss': 0.2567, 'accuracy': 0.9178})
    ploter.addData(x=93, y={'loss': 0.4536, 'accuracy': 0.8742})
    ploter.addData(x=94, y={'loss': 0.3378, 'accuracy': 0.8494})
    ploter.addData(x=95, y={'loss': 0.2145, 'accuracy': 0.9321})
    ploter.addData(x=96, y={'loss': 0.4287, 'accuracy': 0.8964})
    ploter.addData(x=97, y={'loss': 0.3116, 'accuracy': 0.8743})
    ploter.addData(x=98, y={'loss': 0.4283, 'accuracy': 0.8911})
    ploter.addData(x=99, y={'loss': 0.2894, 'accuracy': 0.9257})
    ploter.addData(x=100, y={'loss': 0.3895, 'accuracy': 0.8841})
    # 绘图
    ploter.plot(filename='result.svg')

if __name__ == '__main__':
    demo()
